<a href="https://colab.research.google.com/github/LuizHVicari/Sistemas-Inteligentes/blob/main/HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
lista_maca_peso = [168, 201, 184, 216, 177, 230, 149, 192, 206, 219, 177, 194, 241, 162, 207]
lista_maca_diam = [7.7, 9.2, 8.5, 9.8, 8.1, 10.1, 6.9, 8.8, 9.4, 10.0, 8.2, 9.0, 10.6, 7.5, 9.6]
maca = ['maca' for i in range(15)]

lista_laranja_peso = [150, 162, 170, 182, 195, 204, 213, 221, 234, 246, 257, 266, 278, 287, 296]
lista_laranja_diam = [6, 6.5, 6.8, 7.1, 7.4, 7.7, 8, 8.3, 8.6, 8.9, 9.2, 9.5, 9.8, 10.1, 10.4]
laranja = ['laranja' for i in range(15)]

peso = lista_maca_peso + lista_laranja_peso
diam = lista_maca_diam + lista_laranja_diam
frutas = maca + laranja

df = pd.DataFrame(columns=['peso', 'diametro', 'fruta'])
df['peso'] = peso
df['diametro'] = diam
df['fruta'] = frutas

df['fruta'] = df.apply(lambda x : 0 if x['fruta'] == 'maca' else 1, axis=1)
mat = df.to_numpy()
X, y = mat[:, :-1], mat[:, -1]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)
ss = StandardScaler()
ss.fit(X_train)
X_train = ss.transform(X_train)
X_test = ss.transform(X_test)
X_train, X_test

(array([[-0.04302661,  0.76565612],
        [ 1.90423491,  1.1202758 ],
        [-1.01665737, -1.53937178],
        [-0.3405249 , -1.00744226],
        [-0.69211379, -1.27340702],
        [-1.07074797, -0.74147751],
        [ 1.03878534,  0.32238152],
        [-0.82734028, -0.38685783],
        [ 1.33628363,  0.58834628],
        [-1.55756335, -2.24861113],
        [-0.63802319, -0.03223815],
        [-0.01598131,  0.94296596],
        [ 0.71424176,  0.05641677],
        [ 0.30856227,  1.29758564],
        [ 0.14629048, -0.47551275],
        [-1.23301976, -0.91878734],
        [ 0.36265287, -0.20954799],
        [-0.3675702 ,  0.41103644],
        [-0.17825311,  0.58834628],
        [-0.82734028, -0.29820291],
        [ 0.60606056,  1.38624056],
        [ 2.39105029,  1.65220531]]),
 array([[-0.09711721, -0.74147751],
        [-0.4216608 ,  0.23372661],
        [-1.23301976, -1.80533654],
        [ 0.22742638,  1.1202758 ],
        [ 1.57969132,  0.85431104],
        [ 2.1476426 ,  1.3

In [ ]:
import numpy as np

class Adaline:
    def __init__(self, learning_rate=0.01, num_epochs=50):
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        num_samples, num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0

        for _ in range(self.num_epochs):
            for i in range(num_samples):
                output = self.activation_function(X[i])
                error = y[i] - output
                self.weights += self.learning_rate * X[i] * error
                self.bias += self.learning_rate * error

    def activation_function(self, X):
        return np.dot(X, self.weights) + self.bias

    def predict(self, X):
        pred = list()

        for line in X:
            p = 0 if np.dot(line, self.weights) + self.bias <= 0 else 1
            pred.append(p)

        return np.array(pred)

    def score(self, y, y_predict):
        return np.sum(y == y_predict) / y_predict.shape[0]


In [ ]:
# Create an instance of Adaline classifier
adaline = Adaline(learning_rate=0.1, num_epochs=10000)
adaline.fit(X_train, y_train)

predictions = adaline.predict(X_test)
print(adaline.score(y_test, predictions), adaline.score(adaline.predict(X_train), y_train))

0.75 0.7727272727272727


In [ ]:
print(predictions), (y_test)

[1 1 1 0 1 1 0 1]


(None, array([1., 0., 1., 0., 1., 1., 0., 0.]))

In [ ]:
from sklearn.model_selection import ShuffleSplit
import warnings

warnings.filterwarnings('ignore')

rs = ShuffleSplit(n_splits=5, test_size=0.33)

train_score = np.array([])
test_score = np.array([])

for i,(train_data, test_data)in enumerate(rs.split(df.drop(columns=['fruta']))):
    print(f'Iteração {i+1}')
    X_i = train_data_i.drop(columns=['fruta']).to_numpy()
    y_i = train_data_i['fruta'].to_numpy()

    X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(X_i, y_i, stratify=y_i)

    ss = StandardScaler()
    ss.fit(X_train_i)
    X_train_i = ss.transform(X_train_i)
    X_test_i = ss.transform(X_test_i)

    adaline = Adaline(learning_rate=0.1)

    adaline.fit(X_train_i, y_train_i)

    y_pred_train_i = adaline.predict(X_train_i)
    y_pred_test_i = adaline.predict(X_test_i)

    train_score_i = adaline.score(y_pred_train_i, y_train_i)
    test_score_i = adaline.score(y_pred_test_i, y_test_i)

    train_score = np.append(train_score, train_score_i)
    test_score = np.append(test_score, test_score_i)

    print(f'Precisão na base de treino: {train_score_i}')
    print(f'Precisão na base de teste: {test_score_i}')

print(f'\nPrecisão média:\n\tTeste: {train_score.mean()}\n\tTreino: {test_score.mean()}')
print(f'STD médio:\n\tTeste: {train_score.std()}\n\tTreino: {test_score.std()}')

Iteração 1
Precisão na base de treino: 0.6666666666666666
Precisão na base de teste: 0.8
Iteração 2
Precisão na base de treino: 0.8
Precisão na base de teste: 0.8
Iteração 3
Precisão na base de treino: 0.6666666666666666
Precisão na base de teste: 0.4
Iteração 4
Precisão na base de treino: 0.7333333333333333
Precisão na base de teste: 0.4
Iteração 5
Precisão na base de treino: 0.7333333333333333
Precisão na base de teste: 0.8

Precisão média:
	Teste: 0.72
	Treino: 0.64
STD médio:
	Teste: 0.049888765156985905
	Treino: 0.19595917942265426
